name: Deploy to Tencent Cloud Baota Panel

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      environment:
        description: '部署环境'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  PROJECT_NAME: ai-trading
  DEPLOY_USER: root
  DEPLOY_HOST: ${{ secrets.TENCENT_CLOUD_HOST }}
  DEPLOY_PORT: ${{ secrets.TENCENT_CLOUD_PORT || '22' }}
  DEPLOY_PATH: /www/wwwroot/ai-trading

jobs:
  deploy:
    name: Deploy to Tencent Cloud Baota
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.TENCENT_CLOUD_SSH_KEY }}

    - name: Validate SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "echo 'SSH连接成功'"

    - name: Create deployment package
      run: |
        # 创建部署包
        mkdir -p deploy-package
        
        # 复制必要文件
        cp -r app deploy-package/
        cp -r config deploy-package/
        cp -r core deploy-package/
        cp -r data deploy-package/
        cp -r ai_engine deploy-package/
        cp -r strategies deploy-package/
        cp -r scripts deploy-package/
        cp -r frontend/dist deploy-package/frontend/
        cp requirements.txt deploy-package/
        cp pyproject.toml deploy-package/
        cp docker-compose.yml deploy-package/
        cp Dockerfile deploy-package/
        
        # 创建部署脚本
        cat > deploy-package/deploy.sh << 'EOF'
#!/bin/bash
# 宝塔面板部署脚本

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log() {
    echo -e "${GREEN}[INFO]${NC} $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $(date '+%Y-%m-%d %H:%M:%S') - $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $(date '+%Y-%m-%d %H:%M:%S') - $1"
    exit 1
}

# 备份现有应用
backup_current() {
    if [ -d "$DEPLOY_PATH" ]; then
        log "备份现有应用..."
        backup_dir="/tmp/ai-trading-backup-$(date +%Y%m%d-%H%M%S)"
        cp -r "$DEPLOY_PATH" "$backup_dir"
        log "应用已备份到: $backup_dir"
    fi
}

# 停止服务
stop_services() {
    log "停止服务..."
    
    # 停止Python应用
    if pgrep -f "python.*main:app" > /dev/null; then
        pkill -f "python.*main:app"
    fi
    
    # 停止监控服务
    if pgrep -f "trading_monitor" > /dev/null; then
        pkill -f "trading_monitor"
    fi
    
    sleep 3
}

# 安装依赖
install_dependencies() {
    log "安装Python依赖..."
    
    # 激活虚拟环境
    source /opt/ai-trading/bin/activate
    
    # 安装依赖
    pip install --upgrade pip
    pip install -r requirements.txt
    
    # 安装额外依赖
    pip install psycopg2-binary redis fastapi uvicorn gunicorn \
        ccxt pandas numpy torch torchvision scikit-learn \
        prometheus-client psutil
}

# 配置数据库
setup_database() {
    log "配置数据库..."
    
    # 检查PostgreSQL连接
    if ! pg_isready -h localhost -p 5432 > /dev/null 2>&1; then
        error "PostgreSQL服务未运行"
    fi
    
    # 初始化数据库
    if [ -f "scripts/init_database.sql" ]; then
        psql -h localhost -U ai_trader -d ai_trading -f scripts/init_database.sql
    fi
    
    # 运行数据库迁移
    if [ -f "scripts/database_migration.py" ]; then
        python scripts/database_migration.py
    fi
}

# 配置应用
setup_application() {
    log "配置应用..."
    
    # 创建日志目录
    mkdir -p logs
    
    # 设置权限
    chmod 755 logs
    chmod 644 config/*.py
    
    # 创建环境文件
    if [ ! -f ".env" ]; then
        cat > .env << 'ENVEOF'
DATABASE_URL=postgresql://ai_trader:$DB_PASSWORD@localhost:5432/ai_trading
REDIS_URL=redis://:$REDIS_PASSWORD@localhost:6379/0
DEBUG=False
LOG_LEVEL=INFO
API_KEY=$API_KEY
SECRET_KEY=$SECRET_KEY
ENVEOF
    fi
}

# 启动服务
start_services() {
    log "启动服务..."
    
    # 启动API服务
    nohup python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 --workers 4 > logs/api.log 2>&1 &
    
    # 启动监控服务
    nohup python -m monitoring.trading_monitor > logs/monitor.log 2>&1 &
    
    # 检查服务状态
    sleep 5
    
    if ! pgrep -f "uvicorn" > /dev/null; then
        error "API服务启动失败"
    fi
    
    log "服务启动成功"
}

# 健康检查
health_check() {
    log "执行健康检查..."
    
    # 检查API服务
    if ! curl -f http://127.0.0.1:8000/health > /dev/null 2>&1; then
        error "API健康检查失败"
    fi
    
    # 检查数据库连接
    if ! python -c "
import psycopg2
try:
    conn = psycopg2.connect('postgresql://ai_trader:password@localhost:5432/ai_trading')
    conn.close()
    print('数据库连接正常')
except Exception as e:
    exit(1)
" > /dev/null 2>&1; then
        error "数据库连接失败"
    fi
    
    log "健康检查通过"
}

# 主函数
main() {
    log "开始部署AI量化交易系统..."
    
    backup_current
    stop_services
    install_dependencies
    setup_database
    setup_application
    start_services
    health_check
    
    log "部署完成！"
}

# 执行部署
main "$@"
EOF
        
        chmod +x deploy-package/deploy.sh
        
        # 创建tar包
        tar -czf deploy.tar.gz deploy-package/
        
    - name: Upload deployment package
      run: |
        scp -o StrictHostKeyChecking=no -P $DEPLOY_PORT deploy.tar.gz $DEPLOY_USER@$DEPLOY_HOST:/tmp/

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "
        set -e
        
        echo '开始部署...'
        
        # 解压部署包
        cd /tmp
        tar -xzf deploy.tar.gz
        
        # 备份现有应用
        if [ -d \"$DEPLOY_PATH\" ]; then
            backup_dir=\"/tmp/ai-trading-backup-$(date +%Y%m%d-%H%M%S)\"
            cp -r \"$DEPLOY_PATH\" \"$backup_dir\"
            echo \"应用已备份到: $backup_dir\"
        fi
        
        # 停止服务
        echo '停止服务...'
        pkill -f \"python.*main:app\" || true
        pkill -f \"trading_monitor\" || true
        sleep 3
        
        # 复制文件
        echo '复制文件...'
        rm -rf \"$DEPLOY_PATH\"
        mkdir -p \"$DEPLOY_PATH\"
        cp -r deploy-package/* \"$DEPLOY_PATH\"
        
        # 设置权限
        chown -R www:www \"$DEPLOY_PATH\"
        chmod -R 755 \"$DEPLOY_PATH\"
        
        # 激活虚拟环境并安装依赖
        echo '安装依赖...'
        cd \"$DEPLOY_PATH\"
        source /opt/ai-trading/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        
        # 配置数据库
        echo '配置数据库...'
        if [ -f scripts/init_database.sql ]; then
            psql -h localhost -U ai_trader -d ai_trading -f scripts/init_database.sql
        fi
        
        # 启动服务
        echo '启动服务...'
        nohup python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 --workers 4 > logs/api.log 2>&1 &
        nohup python -m monitoring.trading_monitor > logs/monitor.log 2>&1 &
        
        # 健康检查
        sleep 10
        if curl -f http://127.0.0.1:8000/health > /dev/null 2>&1; then
            echo '✅ 部署成功！'
        else
            echo '❌ 部署失败'
            exit 1
        fi
        "

    - name: Update Nginx configuration
      run: |
        ssh -o StrictHostKeyChecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST "
        # 更新Nginx配置
        cat > /www/server/panel/vhost/nginx/ai-trading.conf << 'NGINXEOF'
server {
    listen 80;
    server_name $DEPLOY_HOST;
    
    # 前端静态文件
    location / {
        root /www/wwwroot/ai-trading/frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    
    # API代理
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # 超时设置
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    # 静态资源缓存
    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control \"public, immutable\";
        root /www/wwwroot/ai-trading/frontend/dist;
    }
    
    # 健康检查
    location /health {
        proxy_pass http://127.0.0.1:8000/health;
        access_log off;
    }
}
NGINXEOF
        
        # 重启Nginx
        nginx -t && nginx -s reload
        "

    - name: Send deployment notification
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: |
          AI量化交易系统部署完成
          环境: ${{ github.event.inputs.environment || 'production' }}
          分支: ${{ github.ref }}
          提交: ${{ github.sha }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}